travis:
  secure:
    BINSTAR_TOKEN: DrcdOqekOygobdIDajmBUQ4jQIlVJM9fGovBzmREEIRXWKLCF4WP78Ws7wbr7lP/LTRPyKWwk/HpCrigdT5jVT+XaMq+PXVT15PIbjvDXcvsMV8xfH2Syk1S6BdOpWSBbZYtwDb4KTiVy0l1mwDtVROtVVw60aZMTg5ev69jybnkcNYHvXW6bt9CBL99y4GR4mcibForWG39CRn06vipT0kdaXgxf6tyivQH1nClxTGk+ts8mClwPZ2OJgdJyqh72oB9OCcV4wPtMk6/1Dy5BMVkwSN7avxBcivpOYIi+47iXuW1Np5kloKHoM5BV+PhHyVIh0lLoamt/GoT8vp8Fipk7ZKkzKAcQ6m60RWvKxTmfgJ20gVgOygWHgy2iE2wBBXaIFih4xKfy8M/cQkbKZ2OialnM3e+5RqCLHjUp24RYBQ/Wow9P9HF+ItN00er/1a616H0kISzW5DFLnMnpTK1p3K2CWBin+ZVAbeXggJo60g+KeYtiEBdXUrK5mjGxcX+a24hCUkxYBjk61pYY/rN7cjOA3jJzpcEDzWdzfIploOdfGyPNmNs5wGckvO+h+egoWhyzlRM68Vrh1lotNGjDAxSzxd3e6DNCs/ZrjBUR6elWwlVbJK9ssl8jSrTR6v+RzC8M8TJbqEkkPiBNlvkoDnkWM6YtOY39oeZzj8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
